export const vehicles = [
  {
    id: 1,
    icon: "🚗",
    model: "Tesla Model 3",
    type: "Car",
    owner: "Sravan Kumar",
    contact: "9876543210",
    price: "₹2,500",
    location: "Mumbai",
    status: "Verified",
  },
  {
    id: 2,
    icon: "🏍️",
    model: "Harley Davidson",
    type: "Bike",
    owner: "Anjali Sharma",
    contact: "9123456789",
    price: "₹1,800",
    location: "Delhi",
    status: "Pending",
  },
  {
    id: 3,
    icon: "🚙",
    model: "BMW X5",
    type: "Car",
    owner: "Ramesh Patel",
    contact: "9988776655",
    price: "₹3,200",
    location: "Bangalore",
    status: "Verified",
  },
];
